# Generated by Django 6.0.4 on 2026-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sample_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
