# Generated by Django 6.0.4 on 2026-04-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_sample_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sample_size',
        ),
    ]
