# Generated by Django 6.0.4 on 2026-04-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
